title: SAM Registry Hive Handle Request
id: WIN-190725024610
collaborators:
  - '@Cyb3rWard0g'
  - '@Cyb3rPandaH'
playbooks_related:
  - WIN-190625024610
creation_date: 2019/07/25
modification_date: 2020/09/20
platform: Windows
attack_mappings:
  - tactics:
      - TA0006
    technique: T1003
    sub_technique: "002"
  - tactics:
      - TA0007
    technique: T1012
    sub_technique: None
hypothesis: Adversaries might be getting a handle to the SAM database to extract credentials in my environment
technical_context: |-
  Every computer that runs Windows has its own local domain; that is, it has an account database for accounts that are specific to that computer.
  Conceptually,this is an account database like any other with accounts, groups, SIDs, and so on.
  These are referred to as local accounts, local groups, and so on.
  Because computers typically do not trust each other for account information, these identities stay local to the computer on which they were created.
offensive_tradecraft: |-
  Adversaries might use tools like Mimikatz with lsadump::sam commands or scripts such as Invoke-PowerDump to get the SysKey to decrypt Security Account Mannager (SAM) database entries (from registry or hive) and get NTLM, and sometimes LM hashes of local accounts passwords.
  
  In addition, adversaries can use the built-in Reg.exe utility to dump the SAM hive in order to crack it offline.
  
  Additional reading
  * https://github.com/OTRF/ThreatHunter-Playbook/tree/master/docs/library/windows/security_account_manager_database.md
  * https://github.com/OTRF/ThreatHunter-Playbook/tree/master/docs/library/windows/syskey.md
test_data:
  metadata: https://securitydatasets.com/notebooks/atomic/windows/credential_access/SDWIN-190625103712.html
  link: https://raw.githubusercontent.com/OTRF/Security-Datasets/master/datasets/atomic/windows/credential_access/host/empire_mimikatz_sam_access.zip
analytics:
  - name: Analytic I
    description: Monitor for any handle requested for the SAM registry hive
    data_sources:
      - name: Windows registry
        event_providers:
        - name: Microsoft-Windows-Security-Auditing
          data_model:
            - relationship: Process requested access Windows registry key
              id: 9DF48A52-109C-47E9-BA9B-B9C27CFCAACF
              event_id: 4656
            - relationship: User requested access Windows registry key
              id: D2E1050F-F94E-4273-B9A5-044E835CF913
              event_id: 4656
    logic: |-
      SELECT `@timestamp`, Hostname, SubjectUserName, ProcessName, ObjectName, AccessMask
      FROM sdTable
      WHERE LOWER(Channel) = "security"
          AND EventID = 4656
          AND ObjectType = "Key"
          AND lower(ObjectName) LIKE "%sam"
known_bypasses:
false_positives:
additional_notes:
research_output:
  - type: Sigma Rule
    link: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_sam_registry_hive_handle_request.yml
  - type: Sigma Rule
    link: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_grabbing_sensitive_hives_via_reg.yml
references: |-
  * http://www.harmj0y.net/blog/activedirectory/remote-hash-extraction-on-demand-via-host-security-descriptor-modification/
  * https://github.com/gentilkiwi/mimikatz/wiki/module-~-lsadump
  * https://adsecurity.org/?page_id=1821#LSADUMPSAM
