#######################################################################################
# Book settings
title: "Threat Hunter Playbook"
logo: images/logo/logo.png
author: Roberto Rodriguez @Cyb3rWard0g
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  This is the first interactive Jupyter book in the infosec community!
execute:
  execute_notebooks: off

html:
  favicon: images/logo/favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://threathunterplaybook.com/

repository:
  url: https://github.com/OTRF/ThreatHunter-Playbook
  branch: master
  path_to_book: docs

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true