title: WDigest Downgrade
id: WIN-190510202010
collaborators:
  - '@Cyb3rWard0g'
  - '@Cyb3rPandaH'
playbooks_related:
creation_date: 2019/05/10
modification_date: 2020/09/20
platform: Windows
attack_mappings:
  - tactics:
      - TA0005
    technique: T1112
    sub_technique: None
hypothesis: Adversaries might have updated the property value UseLogonCredential of HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest to 1 in order to be able to extract clear text passwords from memory contents of lsass.
technical_context: |-
  Windows 8.1 introduced a registry setting that allows for disabling the storage of the users logon credential in clear text for the WDigest provider.
offensive_tradecraft: |-
  This setting can be modified in the property UseLogonCredential for the registry key HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest.
  If this key does not exists, you can create it and set it to 1 to enable clear text passwords.
test_data:
  metadata: https://securitydatasets.com/notebooks/atomic/windows/defense_evasion/SDWIN-190518201922.html
  link: https://raw.githubusercontent.com/OTRF/Security-Datasets/master/datasets/atomic/windows/defense_evasion/host/empire_wdigest_downgrade.tar.gz
analytics:
  - name: Analytic I
    description: Look for any process updating UseLogonCredential registry key value
    data_sources:
      - name: Windows registry
        event_providers:
        - name: Microsoft-Windows-Sysmon/Operational
          data_model:
            - relationship: Process modified Windows registry key value
              id: 25EE8F70-C82B-4C43-A939-10CF156FBBFA
              event_id: 13
    logic: |-
      SELECT `@timestamp`, Hostname, Image, TargetObject
      FROM sdTable
      WHERE Channel = "Microsoft-Windows-Sysmon/Operational"
          AND EventID = 13
          AND TargetObject LIKE "%UseLogonCredential"
          AND Details = 1
known_bypasses:
false_positives:
additional_notes:
research_output:
  - type: Sigma Rule
    link: https://github.com/OTRF/ThreatHunter-Playbook/tree/master/signatures/sigma/sysmon_wdigest_registry_modification.yml
references: |-
  * https://github.com/samratashok/nishang/blob/master/Gather/Invoke-MimikatzWDigestDowngrade.ps1
  * https://blog.stealthbits.com/wdigest-clear-text-passwords-stealing-more-than-a-hash/
