title: Access to Microphone Device
id: WIN-200609225055
collaborators:
  - '@Cyb3rWard0g'
  - '@Cyb3rPandaH'
playbooks_related:
creation_date: 2020/06/09
modification_date: 2020/09/20
platform: Windows
attack_mappings:
  - tactics:
      - TA0009
    technique: T1123
    sub_technique: None
hypothesis: Adversaries might be accessing the microphone in endpoints over the network.
technical_context:
offensive_tradecraft: |-
  An adversary can leverage a computer's peripheral devices (e.g., microphones and webcams) or applications (e.g., voice and video call services) to capture audio recordings for the purpose of listening into sensitive conversations to gather information.
  Based on some research from [@svch0st](https://twitter.com/svch0st) you can to determine when and how long a process had access to the microphone of an endpoint by monitoring the following registry key
    * HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\.
test_data:
  metadata: https://securitydatasets.com/notebooks/atomic/windows/collection/SDWIN-200609225055.html
  link: https://raw.githubusercontent.com/OTRF/Security-Datasets/master/datasets/atomic/windows/collection/host/msf_record_mic.zip
analytics:
  - name: Analytic I
    description: Look for any creation or modification of registry keys under HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\NonPackaged
    data_sources:
      - name: Windows Registry
        event_providers:
        - name: Microsoft-Windows-Sysmon/Operational
          data_model:
            - relationship: Process created Windows registry key
              id: 07EBB983-0817-4A07-813D-4137CE1C847A
              event_id: 12
            - relationship: Process modified Windows registry key value
              id: 25EE8F70-C82B-4C43-A939-10CF156FBBFA
              event_id: 13
            - relationship: Process modified Windows registry key value
              id: 25EE8F70-C82B-4C43-A939-10CF156FBBFA
              event_id: 14
            - relationship: Process modified Windows registry key
              id: 50884412-D21F-478E-810B-0C06A6133CED
              event_id: 14
    logic: |-
      SELECT EventID, Message
      FROM sdTable
      WHERE Channel = 'Microsoft-Windows-Sysmon/Operational'
        AND EventID IN (12,13,14)
        AND LOWER(TargetObject) RLIKE '.*consentstore\\\\\\\microphone.*'
  - name: Analytic II
    description: Look for any creation or modification of registry keys under HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone\NonPackaged
    data_sources:
      - name: Windows Registry
        event_providers:
        - name: Microsoft-Windows-Security-Auditing
          data_model:
            - relationship: Process accessed Windows registry key
              id: 91CBB928-CD58-46F7-90A8-E9B3C53D8269
              event_id: 4663
            - relationship: User accessed Windows registry key
              id: 6CDE6D13-4873-4E88-9F16-72CE2F7ACC84
              event_id: 4663
            - relationship: Process requested access Windows registry key
              id: 9DF48A52-109C-47E9-BA9B-B9C27CFCAACF
              event_id: 4656
            - relationship: User requested access Windows registry key
              id: D2E1050F-F94E-4273-B9A5-044E835CF913
              event_id: 4656
            - relationship: Process modified Windows registry key value
              id: 25EE8F70-C82B-4C43-A939-10CF156FBBFA
              event_id: 4657
            - relationship: User modified Windows registry key value
              id: 229AB2D2-FA13-40AA-AB50-23F26093715C
              event_id: 4657
    logic: |-
      SELECT EventID, Message
      FROM sdTable
      WHERE LOWER(Channel) = 'security'
        AND EventID IN (4656,4663,4657)
        AND LOWER(ObjectName) RLIKE '.*consentstore\\\\\\\microphone.*'
known_bypasses:
false_positives:
additional_notes:
research_output:
  - type: Sigma Rule
    link: https://github.com/OTRF/ThreatHunter-Playbook/blob/master/signatures/sigma/sysmon_camera_microphone_access.yml
  - type: Sigma Rule
    link: https://github.com/OTRF/ThreatHunter-Playbook/blob/master/signatures/sigma/win_camera_microphone_access.yml
references: |-
  * https://medium.com/@7a616368/can-you-track-processes-accessing-the-camera-and-microphone-7e6885b37072
