title: Active Directory Replication User Backdoor
id: WIN-190101151110
collaborators:
  - '@Cyb3rWard0g'
  - '@Cyb3rPandaH'
playbooks_related:
  - WIN-180815210510
creation_date: 2019/01/01
modification_date: 2020/09/20
platform: Windows
attack_mappings:
  - tactics:
      - TA0005
    technique: T1222
    sub_technique: "001"
hypothesis: Adversaries with enough permissions (domain admin) might be adding an ACL to the Root Domain for any user to abuse active directory replication services.
technical_context: |-
  Active Directory replication is the process by which the changes that originate on one domain controller are automatically transferred to other domain controllers that store the same data.
  Active Directory data takes the form of objects that have properties, or attributes.
  Each object is an instance of an object class, and object classes and their respective attributes are defined in the Active Directory schema. The values of the attributes define the object, and a change to a value of an attribute must be transferred from the domain controller on which it occurs to every other domain controller that stores a replica of that object.
offensive_tradecraft: |-
  An adversary with enough permissions (domain admin) can add an ACL to the Root Domain for any user, despite being in no privileged groups, having no malicious sidHistory, and not having local admin rights on the domain controller. This is done to bypass detection rules looking for Domain Admins or the DC machine accounts performing active directory replication requests against a domain controller.
  
  The following access rights / permissions are needed for the replication request according to the domain functional level

  | Control access right symbol | Identifying GUID used in ACE |
  | :-----------------------------| :------------------------------|
  | DS-Replication-Get-Changes | 1131f6aa-9c07-11d1-f79f-00c04fc2dcd2 |
  | DS-Replication-Get-Changes-All | 1131f6ad-9c07-11d1-f79f-00c04fc2dcd2 |
  | DS-Replication-Get-Changes-In-Filtered-Set | 89e95b76-444d-4c62-991a-0facbeda640c |

  Additional reading
  * https://github.com/OTRF/ThreatHunter-Playbook/tree/master/docs/library/active_directory_replication.md
test_data:
  metadata: https://securitydatasets.com/notebooks/atomic/windows/defense_evasion/SDWIN-190301125905.html
  link: https://raw.githubusercontent.com/OTRF/Security-Datasets/master/datasets/atomic/windows/defense_evasion/host/empire_powerview_ldap_ntsecuritydescriptor.zip
analytics:
  - name: Analytic I
    description: Look for any user accessing directory service objects with replication permissions GUIDs
    data_sources:
      - name: Windows active directory
        event_providers:
        - name: Microsoft-Windows-Security-Auditing
          data_model:
            - relationship: User accessed AD Object
              id: 8F2A7CAF-7886-4485-8DBB-BCFDA5A181B9
              event_id: 4662
    logic: |-
      SELECT `@timestamp`, Hostname, SubjectUserName, ObjectName, OperationType
      FROM sdTable
      WHERE LOWER(Channel) = "security"
          AND EventID = 4662
          AND ObjectServer = "DS"
          AND AccessMask = "0x40000"
          AND ObjectType LIKE "%19195a5b_6da0_11d0_afd3_00c04fd930c9%"
  - name: Analytic II
    description: Look for any user modifying directory service objects with replication permissions GUIDs
    data_sources:
      - name: Windows active directory
        event_providers:
        - name: Microsoft-Windows-Security-Auditing
          data_model:
            - relationship: User modified AD Object
              id: C993F59C-9BC7-49CE-AD75-E3F22796719E
              event_id: 5136
    logic: |-
      SELECT `@timestamp`, Hostname, SubjectUserName, ObjectDN, AttributeLDAPDisplayName
      FROM sdTable
      WHERE LOWER(Channel) = "security"
          AND EventID = 5136
          AND lower(AttributeLDAPDisplayName) = "ntsecuritydescriptor"
          AND (AttributeValue LIKE "%1131f6aa_9c07_11d1_f79f_00c04fc2dcd2%"
              OR AttributeValue LIKE "%1131f6ad_9c07_11d1_f79f_00c04fc2dcd2%"
              OR AttributeValue LIKE "%89e95b76_444d_4c62_991a_0facbeda640c%")
known_bypasses:
false_positives:
additional_notes:
research_output:
  - type: Sigma Rule
    link: https://github.com/OTRF/ThreatHunter-Playbook/blob/master/signatures/sigma/win_ad_object_writedac_access.yml
  - type: Sigma Rule
    link: https://github.com/OTRF/ThreatHunter-Playbook/blob/master/signatures/sigma/win_ad_replication_user_backdoor.yml
references: |-
  * https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/1522b774-6464-41a3-87a5-1e5633c3fbbb
  * https://docs.microsoft.com/en-us/windows/desktop/adschema/c-domain
  * https://docs.microsoft.com/en-us/windows/desktop/adschema/c-domaindns
  * http://www.harmj0y.net/blog/redteaming/a-guide-to-attacking-domain-trusts/
  * https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc782376(v=ws.10)
  * https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-drsr/f977faaa-673e-4f66-b9bf-48c640241d47
